<?php

namespace BB\Enums;

enum CodigoEstadoTituloCobranca: int
{
    case NORMAL = 1;
    case MOVIMENTO_CARTORIO = 2;
    case EM_CARTORIO = 3;
    case TITULO_COM_OCORRENCIA_DE_CARTORIO = 4;
    case PROTESTADO_ELETRONICO = 5;
    case LIQUIDADO = 6;
    case BAIXADO = 7;
    case TITULO_COM_PENDENCIA_DE_CARTORIO = 8;
    case TITULO_PROTESTADO_MANUAL = 9;
    case TITULO_BAIXADO_PAGO_EM_CARTORIO = 10;
    case TITULO_LIQUIDADO_PROTESTADO = 11;
    case TITULO_LIQUID_PGCRTO = 12;
    case TITULO_PROTESTADO_AGUARDANDO_BAIXA = 13;
    case TITULO_EM_LIQUIDACAO = 14;
    case TITULO_AGENDADO = 15;
    case TITULO_CREDITADO = 16;
    case PAGO_EM_CHEQUE_AGUARD_LIQUIDACAO = 17;
    case PAGO_PARCIALMENTE_CREDITADO = 18;
    case EM_PROCESSAMENTO_ESTADO_TRANSITORIO = 80;
}